### ISSUE TITLE
Bug in reporting ID of A-OK AC-114 compatible blinds

### ISSUE THREAD

**Issue by icygame** [IndigoDomotics/rfxcom-plugin#15]
To control and monitor blinds using RFXTRX, it is necessary to configure a transmitting device and a receiving device (referred to as BLINDS REMOTE).

In respect of A-OK AC-144 blinds, a work-around is necessary to configure a transmitting device. (It also not possible to configure a receiving device- this may be the same underlying issue but is the subject of a separate issue report).

In order to create a device for controlling A-OK AC-144 blinds (or compatible brands eg Motolux) it is necessary to pick up a house code and unit number from the Indigo log on a remote control button-press and enter that data in the device config for an A-OK_AC-144 device. The house code is reported as a decimal, however there appears to be an error in the conversion from hex. The unit code appears to be a fixed value regardless of the actually unit code.

It is possible to successfully configure a transmitting device using raw hex values derived from RFXmgr or the Indigo logs when debugging reports are switched on. 

The plugin needs a tweak to report the correct house and Unicode values required for configuring the device.

**Comment by Ghawken** [comment]
Try:

Have spent some time sorting this out - and works far better than could have guessed.  Added new device type to cover all Blind types - Turn On/Turn off works and device state is updated by Remote if shares same details:

Use the new BlindsT1234 device for most now.

https://github.com/Ghawken/rfxcom-plugin




#### 2.2.1
#
Add new device type BlindsT1234 for all type=25 Blinds

(replacing A-OK AC114, Brel, and others, these others left alone so can update as wanted)

Adds Support for Dooya Blinds and Remotes

Correctly shows Housecode, unitcode and subtype for ALL these Blinds Remotes

Correctly updates On/Off state of device if command sent via Indigo, OR if Remote button pressed

Add subtype to device Def (should allow other blinds to be controlled)

Add last Command received to device State, lastupdated and type

### **Preferred Usage:**

1. Install, setup Physical Blind, setup working Remote for Blind.
2. Update RFXCOM Plugin (this Plugin) to latest version on github
3. Turn on support for Blinds T1234 in Config
4. Turn on log unknown sensors as error in Plugin Config

5. Press Remote Button on your Blind Remote

Log Should show an Unknown Device Error Msg: (like below)

`RFXCOM Error unknown device detected (type = 25). Select a BlindsT1234 Device from the list of devices
 RFXCOM Error HouseCode (hex)=293301 ,subtype (int)=6 ,unitCode (int)=145`


![](https://github.com/Ghawken/rfxcom-plugin/blob/master/Images/LogUnknownDevice.png?raw=true)


Create a RFXCOM BlindsT1234 Device Adding these Details  (demo image = not the same details!)

![](https://github.com/Ghawken/rfxcom-plugin/blob/master/Images/blindsT1234Device.png?raw=true)


####Functions:

Turn On and Turn Off - will open close Blinds (and update Device State)

Remote will likewise turn on/turn off and the State will be updated in Indigo

Also will show last command/last time updated in device states:


![](https://github.com/Ghawken/rfxcom-plugin/blob/master/Images/deviceStates.png?raw=true)

**Comment by mbendiksen** [comment]
Closed in release 3.0.2.
