### ISSUE TITLE
BLINDS REMOTE device not working

### ISSUE THREAD

**Issue by icygame** [IndigoDomotics/rfxcom-plugin#16]
To control and monitor blinds using RFXTRX, it is necessary to configure a transmitting device and a receiving device (referred to as BLINDS REMOTE).

In respect of A-OK AC-144 blinds, there is are issues preventing the successful creation of the BLINDS REMOTE device. To configure the device, it necessary to pick up data from the Indigo log after pressing a button on the physical remote. A separate, but possibly related issue is that the decimal conversion of Device ID reported in the logs is incorrect.

1. The dialogue indicates that the ID for the remote should be entered as a HEX value - but entering any hex value triggers errors when the device is saved. Entering the Device ID as a decimal value doesn't generate an error.
2. Although there is no immediate error reported, configuring the device with the decimal device ID still generates an unrecognised device entry in the logs when the physical button is pressed.

There is discussion of what appears to be a very similar or identical issue in the Indigo forum, and of a patched version of the plugin that addresses the issue. The forum discussion also indicates that the patched version (which is no-longer accessible) was not incorporated into the main plugin code as currently is in use. That discussion is in this thread, which indicates that the plugin may be incorrectly configured for 'Type 24' rather than 'Type 25' protocol. `https://forums.indigodomo.com/viewtopic.php?f=28&t=10199&start=15`

**Comment by Ghawken** [comment]
Try:

Have spent some time sorting this out - and works far better than could have guessed.  Added new device type to cover all Blind types - Turn On/Turn off works and device state is updated by Remote if shares same details:

https://github.com/Ghawken/rfxcom-plugin




#### 2.2.1
#
Add new device type BlindsT1234 for all type=25 Blinds

(replacing A-OK AC114, Brel, and others, these others left alone so can update as wanted)

Adds Support for Dooya Blinds and Remotes

Correctly shows Housecode, unitcode and subtype for ALL these Blinds Remotes

Correctly updates On/Off state of device if command sent via Indigo, OR if Remote button pressed

Add subtype to device Def (should allow other blinds to be controlled)

Add last Command received to device State, lastupdated and type

### **Preferred Usage:**

1. Install, setup Physical Blind, setup working Remote for Blind.
2. Update RFXCOM Plugin (this Plugin) to latest version on github
3. Turn on support for Blinds T1234 in Config
4. Turn on log unknown sensors as error in Plugin Config

5. Press Remote Button on your Blind Remote

Log Should show an Unknown Device Error Msg: (like below)

`RFXCOM Error unknown device detected (type = 25). Select a BlindsT1234 Device from the list of devices
 RFXCOM Error HouseCode (hex)=293301 ,subtype (int)=6 ,unitCode (int)=145`


![](https://github.com/Ghawken/rfxcom-plugin/blob/master/Images/LogUnknownDevice.png?raw=true)


Create a RFXCOM BlindsT1234 Device Adding these Details  (demo image = not the same details!)

![](https://github.com/Ghawken/rfxcom-plugin/blob/master/Images/blindsT1234Device.png?raw=true)


####Functions:

Turn On and Turn Off - will open close Blinds (and update Device State)

Remote will likewise turn on/turn off and the State will be updated in Indigo

Also will show last command/last time updated in device states:


![](https://github.com/Ghawken/rfxcom-plugin/blob/master/Images/deviceStates.png?raw=true)

**Comment by mbendiksen** [comment]
Closed in 3.0.2.
